### ISSUE TITLE
Toasts dont work

### ISSUE THREAD

**Issue by Xhiro-Yui** [easly1989/ffxiv_act_dfassist#26]
Log from the plugin tab : 

[05:10:21] Q: Matching Stopped
[05:12:56] Q: Matching started for duties: 
[05:12:56]  0. [204] - the Palace of the Dead (Floors 51-60)
[05:12:56] Q: Matching State Updated [the Palace of the Dead (Floors 51-60), 0/0, 0/0, 0/0 | 0]
[05:12:56] Could not find Roulette with 0, report to the dev!
[05:12:56] A: Error while analyzing Message: Method not found: 'Void Advanced_Combat_Tracker.TraySlider.ShowTraySlider(System.String, System.String)'.

----------------------------------------------------------------------------------------
If i go into settings and press "Test Configuration", i get an error pop-up with the (not full) contents below.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'Void Advanced_Combat_Tracker.TraySlider.ShowTraySlider(System.String, System.String)'.
   at DFAssist.Helpers.ToastHelper.OnSendNotification(String title, String message, String testing)
   at DFAssist.Helpers.BaseNotificationHelper`1.SendNotification(String title, String message, String testing)
   at DFAssist.Helpers.DFAssistUIInteractionHelper.TestConfigurationButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I'll provide more details if you need them as I'm not sure what you would want 🤔

**Comment by easly1989** [comment]
Are you using latest version of ACT and latest DFAssist plugin?

Because if it is the case, this means that this method has been changed again 😅

I'll look into it tomorrow as soon as I can!

**Comment by ffxivvillein** [comment]
I had the same error. But it was resolved ACT v3.4.2.262 with the addition of functions were added.

You need update latest version of ACT.

**Comment by Xhiro-Yui** [comment]
Updated to latest ACT and it works now though still see some weird stuff that i dont think i should be seeing?

![image](https://user-images.githubusercontent.com/19362381/64903839-2228b180-d6f3-11e9-9ce4-18c5dde0cc18.png)

----------------------------------------------------------------------------------

Also the log from console : 

[13:24:36] Q: Matching Stopped
[13:25:20] Q: Matching started for duties: 
[13:25:20]  0. [204] - the Palace of the Dead (Floors 51-60)
[13:25:20] Q: Matching State Updated [the Palace of the Dead (Floors 51-60), 0/0, 0/0, 0/0 | 0]
[13:25:21] Could not find Roulette with 0, report to the dev!
[13:25:21] UI: Request Showing Taost received...
[13:25:21] UI: Using Windows Toasts
[13:25:21] UI: Creating new Toast...
[13:25:21] UI: Toast showing, waiting for interaction...
[13:25:21] UI: Telegram notifications are disabled
[13:25:21] UI: Pushbullet notifications are disabled
[13:25:21] Q: Matched [0 - - the Palace of the Dead (Floors 51-60)] - [204 - the Palace of the Dead (Floors 51-60)]
[13:25:21] Could not find Roulette with 0, report to the dev!
[13:25:21] UI: Request Showing Taost received...
[13:25:21] UI: Using Windows Toasts
[13:25:21] UI: Creating new Toast...
[13:25:21] UI: Toast showing, waiting for interaction...
[13:25:21] UI: Telegram notifications are disabled
[13:25:21] UI: Pushbullet notifications are disabled
[13:25:21] Q: Matched [0 - - the Palace of the Dead (Floors 51-60)] - [204 - the Palace of the Dead (Floors 51-60)]
[13:25:24] Q: Matching State Updated [the Palace of the Dead (Floors 51-60), 0/0, 0/0, 0/0 | 0]
[13:25:31] Q: Matching State Updated [the Palace of the Dead (Floors 51-60), 0/0, 0/0, 0/0 | 0]
[13:25:46] UI: Toast Timed out
[13:25:52] Q: Matching State Updated [the Palace of the Dead (Floors 51-60), 0/0, 0/0, 0/0 | 0]
[13:25:52] Q: Entered Instance Area

----------------------------------------------------------------------------------

Otherwise it's fixed, thanks, good work and keep it up 👍

**Comment by easly1989** [comment]
The instance/roulette 0 problem should have ve been fixed, it is really strange.
The main problem for me now to test this out is that I can't test it (I'm not playing right now, usual period of hold from ff 😅)

I'll give another look at the code, and ensure that 0 codes are ignored.

But, being a minor issue, i close this one
Have a safe journey!
