### ISSUE TITLE
Trouble with Discord Push Notifications - English

### ISSUE THREAD

**Issue by jekyll87** [easly1989/ffxiv_act_dfassist#51]
Followed wiki to set up push notifications on Discord. The notifications are coming through on the correct channel but the @username isn't actually working for me. The bot types it, but it isn't a normal mention. The username is written correctly.

![Capture](https://user-images.githubusercontent.com/58228225/69656333-5d762380-1046-11ea-87e0-ce6c52c02518.JPG)

**Comment by easly1989** [comment]
It may be related to the fact that it is a webhook.. But honestly i don't know discord api so well.
also, your bot has the same name of the username you are trying to mention, it may be a problem too.

As a last test, i would try to put your username followed by your tag (#somenumbers), it should identify you exactly and may work.

Let me know the result of you are able to test,
So that i can look for a fix or add some detail in the wiki page

**Comment by jekyll87** [comment]
The "username" field also dictates the bot name, it seems. I changed it to my tag and it changed also. Didn't ping me either this time.

![image](https://user-images.githubusercontent.com/58228225/69660473-679c2000-104e-11ea-82ed-25a94a474634.png)

**Comment by easly1989** [comment]
So, I'll try to find some documentation about the method I use to send the notifications

It seems like the username is actually the hook name, and use DFassist as the bot name..

I'll do a pre_build tomorrow with this modifications and link it here so you can test it 🤞

**Comment by jekyll87** [comment]
Sounds good. I can test it for you. Thanks!

**Comment by easly1989** [comment]
[DFAssist_2.2.8_pre.zip](https://github.com/easly1989/ffxiv_act_dfassist/files/3896427/DFAssist_2.2.8_pre.zip)

Here it is, just to test the discord notification (as I still have to find the opcodes for the instances)

**Comment by jekyll87** [comment]
Tested. The name of the bot is correct now, but no ping. Idk if it helps (or if you use discord), but typically a tab/enter after the user name in discord forces the autofill of the name and actually sends the notification.

![image](https://user-images.githubusercontent.com/58228225/69727190-0593f700-10f0-11ea-9dd9-8ae3efeba8fe.png)

**Comment by easly1989** [comment]
[DFAssist_2.2.8_pre2.zip](https://github.com/easly1989/ffxiv_act_dfassist/files/3897174/DFAssist_2.2.8_pre2.zip)

So, I've opted for a different route, using the Discord.NET library.
Now it should work (hopefully, as I can't test it at work).

Instead of the Username you have to put your user ID (you can get it from Discord itself, or writing the command \@user (I've read about this around the web ^^'.. I'm not a discord user myself so.. ^^')

let me know the output so that I can fix the rest of the things (strings like username should be userid for example) and push the next release.

**Comment by jekyll87** [comment]
I receive this "Unhandled Exception in ACT" when I try to hit test

System.TypeLoadException - Could not load type 'Discord.EmbedBuilder' from assembly 'Discord.Net.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at DFAssist.Helpers.DiscordHelper.OnSendNotification(String title, String message, String testing)
   at DFAssist.Helpers.BaseNotificationHelper`1.SendNotification(String title, String message, String testing)
   at DFAssist.Helpers.DFAssistUIInteractionHelper.TestConfigurationButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

DFAssist.Helpers.DiscordHelper, DFAssist.Plugin, Version=2.2.8.0, Culture=neutral, PublicKeyToken=null

**Comment by easly1989** [comment]
[DFAssist_2.2.8_pre3.zip](https://github.com/easly1989/ffxiv_act_dfassist/files/3897377/DFAssist_2.2.8_pre3.zip)

Yep, i was not loading the needed assemblies required by the new library Discord.Net.
It should be loaded just fine now

**Comment by jekyll87** [comment]
Got a similar exception.

System.TypeLoadException - Could not load type 'Discord.EmbedBuilder' from assembly 'Discord.Net.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at DFAssist.Helpers.DiscordHelper.OnSendNotification(String title, String message, String testing)
   at DFAssist.Helpers.BaseNotificationHelper`1.SendNotification(String title, String message, String testing)
   at DFAssist.Helpers.DFAssistUIInteractionHelper.TestConfigurationButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

DFAssist.Helpers.DiscordHelper, DFAssist.Plugin, Version=2.2.8.0, Culture=neutral, PublicKeyToken=null

**Comment by easly1989** [comment]
When I try it locally it seems to work.
I've pushed version 2.2.8 release officially (as I found the opcode for the duty matched packet).
You may want to try and cleanly install the plugin.

let me know if doing so helps or not

**Comment by jekyll87** [comment]
Clean install helped with that. The settings don't seem to be saving though so when I exit > enter ACT I have to re-enter the webhook URL and ID. Any thoughts on that last bit?

![image](https://user-images.githubusercontent.com/58228225/69738356-fb7bf380-1103-11ea-8407-bebb6bf4e47e.png)

**Comment by easly1989** [comment]
At least it is working 😂
The problem with settings not saved could be a missed setting serialization.. I'll watch into it asap and push another release (also with the correct strings for user id)

Thank you for your testings! 😊

**Comment by jekyll87** [comment]
Thank you for helping! Will look forward to the settings fix :)
