### ISSUE TITLE
Discord notification not working and returning error

### ISSUE THREAD

**Issue by KagomeKagome** [easly1989/ffxiv_act_dfassist#56]
```
System.MissingMethodException - Method not found: 'Void Discord.Webhook.DiscordWebhookClient..ctor(System.String)'.
   at DFAssist.Helpers.DiscordHelper.OnSendNotification(String title, String message, String testing)
   at DFAssist.Helpers.BaseNotificationHelper`1.SendNotification(String title, String message, String testing)
   at DFAssist.Helpers.DFAssistUIInteractionHelper.TestConfigurationButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

DFAssist.Helpers.DiscordHelper, DFAssist.Plugin, Version=2.2.10.0, Culture=neutral, PublicKeyToken=null
```

I had the Discord webhook set up exactly as it was before the newer versions. I've tried a fresh install of the most recent release (deleting everything including the settings in Appdata). Upon setting up the Discord notifications on the fresh install, this error still happened.

**Comment by easly1989** [comment]
I'll look into it tomorrow, but it seems like a newer (or different version) of Discord.Webhook library is loaded that does not have that constructor for the DiscordWebhookClient.

I Would try to load just the FFXIV_ACT_Plugin and DFAssist to see if it works.
After that load every other plugin you have and see which one is causing the conflict.

Beside this, Tomorrow i'll check if there is an update for the library and will ensure that it is using the latest version

**Comment by easly1989** [comment]
Just checked and I'm using the latest build of Discord.Net.Webhook.
So if the problem persist, it may really be related to another plugin that is loaded before DFAssist that is using an obsolete Discord.Net.Webhook library.

let me know if you are able to do the test, and if this was the problem

**Comment by KhloeLeclair** [comment]
I've been seeing this exact exception as well, and it was definitely another plugin conflicting on my end. Specifically, https://github.com/anoyetta/ACT.Hojoring from which I use TTSYukkuri for TTS audio. It apparently has a Discord integration that I've never used. Unfortunately, loading DFAssist first causes that plugin's core functionality to break, but that isn't the fault of this project.
