### ISSUE TITLE
discord integration not working?

### ISSUE THREAD

**Issue by Tambone** [easly1989/ffxiv_act_dfassist#83]
trying to add the discord integration just gives me this error:

System.ArgumentException - The given webhook Url was not in a valid format. The webhook Id could not be parsed.
Parameter name: webhookUrl
   at Discord.Webhook.DiscordWebhookClient.ParseWebhookUrl(String webhookUrl, UInt64& webhookId, String& webhookToken)
   at Discord.Webhook.DiscordWebhookClient..ctor(String webhookUrl, DiscordRestConfig config)
   at DFAssist.Helpers.DiscordHelper.OnSendNotification(String title, String message, String testing)
   at DFAssist.Helpers.BaseNotificationHelper`1.SendNotification(String title, String message, String testing)
   at DFAssist.Helpers.DFAssistUIInteractionHelper.TestConfigurationButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Discord.Webhook.DiscordWebhookClient, Discord.Net.Webhook, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null

**Comment by acraist** [comment]
> trying to add the discord integration just gives me this error:
> 
> System.ArgumentException - The given webhook Url was not in a valid format. The webhook Id could not be parsed.
> Parameter name: webhookUrl
> at Discord.Webhook.DiscordWebhookClient.ParseWebhookUrl(String webhookUrl, UInt64& webhookId, String& webhookToken)
> at Discord.Webhook.DiscordWebhookClient..ctor(String webhookUrl, DiscordRestConfig config)
> at DFAssist.Helpers.DiscordHelper.OnSendNotification(String title, String message, String testing)
> at DFAssist.Helpers.BaseNotificationHelper`1.SendNotification(String title, String message, String testing)
> at DFAssist.Helpers.DFAssistUIInteractionHelper.TestConfigurationButton_Click(Object sender, EventArgs e)
> at System.Windows.Forms.Control.OnClick(EventArgs e)
> at System.Windows.Forms.Button.OnClick(EventArgs e)
> at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
> at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
> at System.Windows.Forms.Control.WndProc(Message& m)
> at System.Windows.Forms.ButtonBase.WndProc(Message& m)
> at System.Windows.Forms.Button.WndProc(Message& m)
> at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> Discord.Webhook.DiscordWebhookClient, Discord.Net.Webhook, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null

change the first part of the url from 'discord.com' to 'discordapp.com'

**Comment by Tambone** [comment]
thank you! that worked but i dont think the @ is working. in the wiki it shows actually @ing the person but im just getting this: with the !infront of my tag
https://imgur.com/a/94NbdhC

**Comment by acraist** [comment]
You need to put your discord userID.
Settings > Advanced > Developer Mode On
Now you can copy your ID
https://imgur.com/9mCxmK1
